# Generated by Django 4.1.5 on 2023-02-05 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Self", "Self"), ("OnBehalf", "OnBehalf")],
                        max_length=255,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("age_range", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestigationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("type_description", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StateRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SymptomQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("c", "Child"), ("a", "Adult")], max_length=1
                    ),
                ),
                ("is_active", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Township",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "state_region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.stateregion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TBReferralClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField()),
                ("site_name", models.CharField(max_length=255)),
                (
                    "site_type",
                    models.CharField(
                        choices=[("1", "Referral"), ("2", "Register")], max_length=255
                    ),
                ),
                (
                    "channel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.channel",
                    ),
                ),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.organization",
                    ),
                ),
                (
                    "state_region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.stateregion",
                    ),
                ),
                (
                    "township_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.township",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestigationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("result_description", models.CharField(max_length=255)),
                (
                    "investigation_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.investigationtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientTBTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("is_registered_for_tx", models.BooleanField()),
                ("tx_regime", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientTBReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("is_willing_to_be_referred", models.BooleanField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientTBConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("is_bat_confirmed", models.BooleanField()),
                (
                    "tb_diagnosis",
                    models.CharField(
                        choices=[("1", "Positive"), ("2", "Negative")], max_length=1
                    ),
                ),
                ("diagnosis_date", models.DateField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientSymptomQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("answer", models.BooleanField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.symptomquestion",
                    ),
                ),
                (
                    "stage_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.stage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientSocialPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
                (
                    "social_platform_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.socialplatform",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientRefRegLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("action_date", models.DateField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[("1", "Referral"), ("2", "Register")], max_length=1
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
                (
                    "site_location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.sitelocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientReachInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("is_reached_to_referral_site", models.BooleanField()),
                ("reached_date", models.DateField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
                (
                    "referred_location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.clientrefreglocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=255)),
                (
                    "phone_type",
                    models.CharField(
                        choices=[("1", "Primary"), ("2", "Additional")],
                        default="1",
                        max_length=255,
                    ),
                ),
                ("can_be_contacted", models.BooleanField(null=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientInvestigatedResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("taken_investigation_date", models.DateField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
                (
                    "taken_investigation_result_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.investigationresult",
                    ),
                ),
                (
                    "taken_investigation_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.investigationtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-taken_investigation_date"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("social_media_id", models.CharField(max_length=255)),
                ("social_media_name", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("count", models.PositiveSmallIntegerField()),
                ("current_attempt_date", models.DateField()),
                ("next_attempt_date", models.DateField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.client",
                    ),
                ),
                (
                    "stage_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="callcenter.stage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
