# Generated by Django 4.1.5 on 2023-02-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0002_alter_client_age_range"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"verbose_name_plural": "06. Channels"},
        ),
        migrations.AlterModelOptions(
            name="investigationresult",
            options={"verbose_name_plural": "10. InvestigationResults"},
        ),
        migrations.AlterModelOptions(
            name="investigationtype",
            options={"verbose_name_plural": "09. InvestigationTypes"},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name_plural": "07. Organizations"},
        ),
        migrations.AlterModelOptions(
            name="sitelocation",
            options={"verbose_name_plural": "08. SiteLocations"},
        ),
        migrations.AlterModelOptions(
            name="socialplatform",
            options={"verbose_name_plural": "03. Social platforms"},
        ),
        migrations.AlterModelOptions(
            name="stage",
            options={"verbose_name_plural": "01. Stages"},
        ),
        migrations.AlterModelOptions(
            name="stateregion",
            options={"verbose_name_plural": "04. States regions"},
        ),
        migrations.AlterModelOptions(
            name="symptomquestion",
            options={"verbose_name_plural": "02. Symptom questions"},
        ),
        migrations.AlterModelOptions(
            name="township",
            options={"verbose_name_plural": "05. Townships"},
        ),
        migrations.AddField(
            model_name="sitelocation",
            name="site_name_mm",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
