# Generated by Django 4.1.5 on 2023-02-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0003_alter_channel_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitelocation",
            old_name="site_name",
            new_name="site_address",
        ),
        migrations.RenameField(
            model_name="sitelocation",
            old_name="site_name_mm",
            new_name="site_address_mm",
        ),
        migrations.AddField(
            model_name="sitelocation",
            name="clinic_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitelocation",
            name="clinic_name_mm",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
