# Generated by Django 4.1.5 on 2023-02-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0004_rename_site_name_sitelocation_site_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitelocation",
            name="clinic_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sitelocation",
            name="clinic_name_mm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
