# Generated by Django 4.1.5 on 2023-02-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0005_alter_sitelocation_clinic_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[("Self", "Self"), ("Family", "Family")], max_length=255
            ),
        ),
    ]
