# Generated by Django 4.1.5 on 2023-02-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0006_alter_client_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientphone",
            name="can_be_contacted",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
