# Generated by Django 4.1.5 on 2023-02-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0007_alter_clientphone_can_be_contacted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotclient",
            name="client_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chatbot_clients",
                to="callcenter.client",
            ),
        ),
        migrations.AlterField(
            model_name="clientphone",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_phones",
                to="callcenter.client",
            ),
        ),
        migrations.AlterField(
            model_name="clientsymptomquestionanswer",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_symptom_questions_answers",
                to="callcenter.client",
            ),
        ),
        migrations.AlterField(
            model_name="clientsymptomquestionanswer",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_symptom_questions",
                to="callcenter.symptomquestion",
            ),
        ),
        migrations.AlterField(
            model_name="tbreferralclient",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tb_referral_clients",
                to="callcenter.client",
            ),
        ),
    ]
