# Generated by Django 4.1.5 on 2023-02-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0008_alter_chatbotclient_client_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotclient",
            name="client_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="callcenter.client",
            ),
        ),
        migrations.AlterField(
            model_name="clientphone",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="callcenter.client"
            ),
        ),
        migrations.AlterField(
            model_name="tbreferralclient",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="callcenter.client"
            ),
        ),
    ]
