# Generated by Django 4.1.5 on 2023-02-19 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0011_rename_client_id_callattempt_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="callcenter.stage",
            ),
        ),
    ]
