# Generated by Django 4.1.5 on 2023-02-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0012_client_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientreachinfo",
            name="referred_location",
        ),
    ]
