# Generated by Django 4.1.5 on 2023-02-21 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0013_remove_clientreachinfo_referred_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienttbtreatment",
            name="registered_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tbreferralclient",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("BelowFifteen", "BelowFifteen"),
                    ("FifteenAndAbove", "FifteenAndAbove"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
