# Generated by Django 4.1.5 on 2023-02-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0014_clienttbtreatment_registered_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clienttbconfirmation",
            name="tb_diagnosis",
            field=models.CharField(
                choices=[("Positive", "Positive"), ("Negative", "Negative")],
                max_length=8,
            ),
        ),
    ]
