# Generated by Django 4.1.5 on 2023-02-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0015_alter_clienttbconfirmation_tb_diagnosis"),
    ]

    operations = [
        migrations.CreateModel(
            name="TxRegime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="clienttbtreatment",
            name="tx_regime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="callcenter.txregime"
            ),
        ),
    ]
