# Generated by Django 4.1.5 on 2023-02-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0016_txregime_alter_clienttbtreatment_tx_regime"),
    ]

    operations = [
        migrations.AddField(
            model_name="txregime",
            name="is_active",
            field=models.BooleanField(null=True),
        ),
    ]
