# Generated by Django 4.1.5 on 2023-02-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0017_txregime_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="txregime",
            options={"verbose_name_plural": "11. TxRegimes"},
        ),
        migrations.AddField(
            model_name="township",
            name="name_mm",
            field=models.CharField(default="", max_length=255),
        ),
    ]
