# Generated by Django 4.0.6 on 2023-06-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0019_investigationresult_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelocation',
            name='provider_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitelocation',
            name='provider_name_mm',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
